### ISSUE TITLE
翻訳

### ISSUE THREAD

**Issue by dreamkyast0** [yoshihiro-shu/draft-next#29]
YOSSY NOTE -> YOSSY'S NOTE
AJAILE -> AGILE
BUSSINESS -> BUSINESS

**Comment by yoshihiro-shu** [comment]
@ichigozero 

対応しました！

![image](https://github.com/yoshihiro-shu/tech-blog-frontend/assets/84740493/683bc572-d043-4551-bf23-57465afea6a7)

**Comment by yoshihiro-shu** [comment]
@ichigozero 
対応しました！

<img width="1333" alt="image" src="https://github.com/yoshihiro-shu/tech-blog-frontend/assets/84740493/693d8b52-f4e8-444a-9f56-b9ad378edb26">
